dist: bionic
language: python
sudo: false

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8-dev
  - 3.9-dev
  - pypy2
  - pypy3

env:
  global:
    - ASTTOKENS_SLOW_TESTS=1
    - COVERALLS_PARALLEL=true

before_install:
  - pip install --upgrade setuptools>=44 wheel setuptools_scm[toml]>=3.4.3 pep517
  - pip install --upgrade coveralls

install:
  #- python3 -m pep517.build . # replace the following command with this one when you drop python 2
  - python ./setup.py bdist_wheel
  - export WHLNAME=./dist/asttokens-0.CI-py2.py3-none-any.whl
  - mv ./dist/*.whl $WHLNAME
  - pip install --upgrade --pre "$WHLNAME[test]"

script:
  - travis_wait 30 coverage run --branch --include='asttokens/*' -m pytest --junitxml=./rspec.xml
  - coverage report -m

after_success:
  - coveralls

notifications:
  webhooks: https://coveralls.io/webhook
